### ISSUE TITLE
Complete initial goals

### ISSUE THREAD

**Issue by kwalcock** [clulab/pdf2txt#10]
1. The first is obviously extracting the text from the PDF.
2. Then we should have a step for Unicode normalization, based on the mapping in this file:
https://github.com/clulab/processors/blob/master/main/src/main/resources/org/clulab/processors/bionlp/unicode_to_ascii.tsv
This is needed to avoid the weird hyphen issue we ran into. There are other Unicode chars that are similar.

3. Add implicit end-of-sentence punctuation. That is, the generated text often include 2+ new lines to indicate different paragraphs. For example:

This is a Title

This is where the first paragraph begins...

Because sometimes lines that end a paragraph do not include end-of-sentence periods, processors thinks that the whole thing is a single sentence, which is wrong. I propose the following heuristic: if text is separated by 2+ new lines, and the line on top does not end with end-of-sentence punctuation, and " ." to it. That is, the text above becomes:

This is a Title .

This is where the first paragraph begins...

4. Merge broken words ("-" followed by 1 white space). That is, some words are separated into two fragments due to end of lines. In the generated text, they will show up separated by a dash followed by a white space, e.g.: "dis- close". These should be merged.

5. Merge broken words using language models. Similarly, some words are broken without the dash. In this case, we should probabilistically merge them using a language model (LM). For example, take the sentence:

"They decided to dis close something"

Using a language model, we should check if P("dis"|"They decided to") is larger than P("disclose"|"They decided to"). If not, then the two tokens should be merged into one. Masha and Mithun can help populating an API that computes P(text|text_that_precedes_it).

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !
