### ISSUE TITLE
Merge broken numbers

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/pdf2txt#13]
"To date , the seedlings are evaluated at 42 ,807 ha  for this current campaign against 49,356 ha in SSC 2020 at the same period , a decrease of 6,549 ha in cultivated areas ."

**Comment by MihaiSurdeanu** [comment]
In the above sentence, the number "42 ,807" has an extra space before the comma. I have this mistake several times. I propose to merge such cases back into a single number

**Comment by kwalcock** [comment]
Will do.

**Comment by kwalcock** [comment]
This was addressed with #15 and #16.
