### ISSUE TITLE
space-separated large numbers 

### ISSUE THREAD

**Issue by maxaalexeeva** [clulab/pdf2txt#48]
Some large numbers have thousands separated with a space, so they get tokenized separately. Do we want to normalize them somewhere in reading projects or during pdf to txt conversion? Here's a screenshot from [a pdf ](https://hal.archives-ouvertes.fr/hal-00886297/document) with a couple of examples:

![Screenshot from 2022-06-19 21-28-04](https://user-images.githubusercontent.com/31713912/174525429-ea3e1d05-8c3e-4cd2-ac6b-38fb176d701c.png)

**Comment by MihaiSurdeanu** [comment]
I think this would be hard to detect... What do you think @kwalcock ?

**Comment by kwalcock** [comment]
The pdf2txt converter already has this capability.  However, it is not turned on by default.  I don't remember exactly why, but perhaps it was thought that something could consider those spaces significant.  If you are working with the github project, you can change
```scala
case class Hyperparameters(joinWithSpaces: Boolean = false)
```
to use `true`.

The setting isn't available from the command line or a configuration file.  I'll at least add the latter for now.  The command line is already awfully crowded.

**Comment by kwalcock** [comment]
It probably won't stay this way forever, but temporarily one can make a configuration file like `habitus.conf` containing
```
Pdf2txt {
  numberParameters {
    joinWithSpaces = true
  }
}
```
and then call `PdfToTextApp` with `-conf habitus`.  Otherwise one can edit `Pdf2txt.conf` and change the value from `false` to `true`.

**Comment by maxaalexeeva** [comment]
@kwalcock thank you!
